export { default as desktopLight } from "./bg-desktop-light.jpg";
export { default as desktopDark } from "./bg-desktop-dark.jpg";
export { default as mobDark } from "./bg-mobile-dark.jpg";
export { default as mobLight } from "./bg-mobile-light.jpg";
export { default as TODO } from "./TODO.png";
export { default as Moon } from "./icon-moon.svg";
export { default as Sun } from "./icon-sun.svg";
export { default as xIcon } from "./icon-cross.svg";
export { default as checkIcon } from "./icon-check.svg";
